### ISSUE TITLE
Collections in Subdirectories

### ISSUE THREAD

**Issue by justinenevans** [aksakalli/jekyll-doc-theme#21]
Hey, love this theme. Great for grouping relative content into separate exploratory topics!

I'm trying to get _docs_nav.html_ and _section-nav.html_ to function for subdirectories as individual collections; in other words, only pages within said subdirectory will populate in the side nav. For example:
```yml
animal-species/
├── _docs/
│   ├── _mammals/
│   │  ├── page01.md
│   │  └── page02.md
│   ├── _reptiles/
│   │  ├── page01.md
│   │  └── page02.md
```

I'm newer to Liquid and collections, so this is most-likely a basic question, but I'm stumped and Google isn't helping. I'm trying to keep the directory structure as tight as possible, with as much nesting that's feasible.  I originally set the nav files for each individual subfolder and module using appending and prepending, which worked, but was a logistical nightmare. I there a way to get the site to populate collections separately as per subdirectory?  I've tried adding to `_config`:

```yml
collections_dir: docs
collections:
  mammals:
    permalink: /:collection/:path/
    output: true
  reptiles:
    output: true
    permalink: /:collection/:path/
```
running Jekyll 3.7.0, but I lose the page entirely (404). Adding `includes: ['_mammals']` helps to an extent, but it only returns HTML.

Is there an easy command or fix for this? With 100+ site pages, I only want the nav to paginate high-level related content from master pages, such as "Mammals". I really appreciate your ideas on this! Thank you!
