### ISSUE TITLE
Creating a new docs collection

### ISSUE THREAD

**Issue by AWatk** [aksakalli/jekyll-doc-theme#22]
What needs to be done if I want to have a new collection, available on the top navigation bar, that has the same functionality as `Docs`? Essentially, instead of having `Docs | Blog` on the top navigation bar, I want `Docs | OtherDocs | Blog`.  Where `OtherDocs` has its own independent sidebar and such.

I feel that this is a really simple thing that I am just missing because I'm so new to jekyll site generation.

Thanks!

**Comment by AWatk** [comment]
This was a sort of a broad question. After messing around for a bit longer, I've gotten very close to what I need.  The steps I've done so far are:

**1.** Created the `OtherDocs` folder
```bash
cp -r _docs _otherdocs
```

**2.** Update front matter within `_otherdocs` to have new permalinks

```yaml
---
title: Welcome
permalink: /otherdocs/home/
redirect_from: /otherdocs/index.html
---
```

**3.** Updated `_config.yml`

```
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

- scope:
    path: _otherdocs
    type: otherdocs
  values:
    layout: docs
    sectionid: otherdocs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  otherdocs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
```

**4.** Updated `topnav.html`

```html
 <ul class="nav navbar-nav">
              <li {% if page.sectionid=='docs' %} class="active" {% endif %}><a href="{{ "/docs/home/" | prepend: site.baseurl }}">Docs</a></li>
	      <li {% if page.sectionid=='otherdocs' %} class="active" {% endif %}><a href="{{ "/otherdocs/home/" | prepend: site.baseurl }}">OtherDocs</a></li>
                <li {% if page.sectionid=='blog' %} class="active" {% endif %}><a href="{{ site.posts.first.url | prepend: site.baseurl }}">Blog</a></li>
            </ul>
```

and that gets me to the point where all that is left is to correct the sidebar. This looks to be done in `docs_nav.html`, , specifically to look to a unique `.yml` file for each document collection instead of the default `docs.yml`, but I'm unsure if there are any other places that need to be touched.

**Comment by AWatk** [comment]
The last two steps that were required were to:

**5.** Create a new data file at `_data/otherdocs.yml`

Since in this toy example `OtherDocs` has the same content as `Docs` the data file is also the same

```yaml
- title: Getting Started
  docs:
  - home
  - themes
  - customization

- title: Examples
  docs:
  - cheatsheet
  - font-awesome
  - bootstrap
```

**6.** Modify `docs_nav.html` and `section_nav.html`  to use `{{ page.sectionid }}` instead of hardcoding `docs`

```
{% assign docname = page.sectionid %}
{% assign dir = docname | prepend: "/" | append: "/" %}
{% assign docs = site.data[docname] | map: 'docs' | join: ',' | split: ',' %}
```
Then find and replace every usage of `"/docs/"` with `dir`
