### ISSUE TITLE
Sidebar not working

### ISSUE THREAD

**Issue by tessamerrill** [aksakalli/jekyll-doc-theme#43]
Hi there, I'm trying to create some documentation for a repository of mine. I currently have this in docs.yml:
```
- title: Cybersecurity
  docs:
    - title: Browsing The Internet Safely
      path: browsing
    - title: How To Keep Your Information Safe
      path: security
```

It doesn't show up in the sidebar when I test it. just an empty collapse menu. 

Inside those two Markdown files is this:

browsing.md
```
---
title: Browsing The Internet Safely
permalink: /docs/cybersecurity/internet
---
```
security.md
```
---
title: How To Keep Your Information Safe
permalink: /docs/cybersecurity/privacy
---
```
If I go to those links in the browser, it shows up and works, but they don't show up in the sidebar.

What am I doing wrong, and how can I fix it?

Thanks!

**Comment by aksakalli** [comment]
Hi,

your `docs.yml` should look like this:

```yaml
- title: Cybersecurity
  docs:
  - browsing
  - security
```

similar to the default [docs.yml](https://github.com/aksakalli/jekyll-doc-theme/blob/gh-pages/_data/docs.yml), you set the title in the actual `*.md` document.
